version: 0.2

env:
  secrets-manager:
    DATABASE_PASS: "my-app-secrets:DB_PASSWORD"

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Starting the build process"

  build:
    commands:
      - echo "Compiling and testing code using secured password"
      - mvn test

  post_build:
    commands:
      - echo "Build completed"
      - mvn package

artifacts:
  files:
    - target/*.jar